### ISSUE TITLE
Create realm coupling possible interfaces

### ISSUE THREAD

**Issue by eguil** [ES-DOC/esdoc-project#14]
List possible physical interfaces in a master configuration file in esdoc-docs/cmip6/coupling/possible_physical_interfaces.txt

**Comment by davidhassell** [comment]
It was decided that that all 7*8=56 options would be provided

**Comment by davidhassell** [comment]
The 56 possibilities will be ordered so that the most important one are at the top:

atmos to ocean
ocean to atmos
atmos to seaice
seaice to atmos
ocean to seaice
seaice to ocean
atmos to land
land to atmos
atmos to landice (check)
atmos to aerosols
aerosols to atmos
atmos to atmchem
atmchem to atmos
ocean to ocnbgchem
atmos to ocnbgchem
land to ocnbgchem
ocnbgchem to ocean

**Comment by davidhassell** [comment]
Coupling spreadsheets now in play, e.g. https://github.com/ES-DOC-INSTITUTIONAL/cccr-iitm/blob/master/cmip6/models/iitm-esm/cmip6_cccr-iitm_iitm-esm_coupling.xlsx
